### ISSUE TITLE
Add ability to manually resize panes

### ISSUE THREAD

**Issue by damassi** [aaronjensen/atom-painless-panes#2]
Noticed that when this plugin is enabled draggable resizing is no longer available.  Is this a feature that has yet to be implemented or a hard requirement?

**Comment by aaronjensen** [comment]
tbh, I'm not sure the best way to do it. The whole thing w/ this is that it takes over control completely, if you drag it, what would that do, lock that individual slider but still auto size the others? Hold until you change panes? I couldn't think of a good way to do it. I'm open to suggestions on it... in the meantime, I just use the toggle key if I need to.

I also hope for it to be good enough that you don't really need/want to drag them... but maybe that's too utopian :smile:

**Comment by damassi** [comment]
It's a rad plugin regardless :) Makes sense.

**Comment by aaronjensen** [comment]
Thanks!
